"""
Tests for POST /expense-categories.

Generated by /new-endpoint expense-category POST, backed by the
expense_categories table added to database/db.py.
"""

import pytest
import database.db as db_module
from app import app as flask_app
from database.db import init_db
from werkzeug.security import generate_password_hash


@pytest.fixture()
def app(tmp_path, monkeypatch):
    db_file = str(tmp_path / "test_spendly.db")
    monkeypatch.setattr(db_module, "DB_PATH", db_file)

    flask_app.config.update({
        "TESTING": True,
        "SECRET_KEY": "test-secret",
        "WTF_CSRF_ENABLED": False,
    })

    with flask_app.app_context():
        init_db()
        yield flask_app


@pytest.fixture()
def logged_in_client(app):
    client = app.test_client()

    from database.db import get_db
    conn = get_db()
    conn.execute(
        "INSERT INTO users (name, email, password_hash) VALUES (?, ?, ?)",
        ("Category Test User", "category-test@example.com", generate_password_hash("pass1234")),
    )
    conn.commit()
    user_id = conn.execute(
        "SELECT id FROM users WHERE email = ?", ("category-test@example.com",)
    ).fetchone()["id"]
    conn.close()

    with client.session_transaction() as sess:
        sess["user_id"] = user_id

    return client


def test_create_expense_category_requires_login(app):
    client = app.test_client()
    response = client.post("/expense-categories", json={"name": "Groceries"})
    assert response.status_code == 401


def test_create_expense_category_rejects_missing_name(logged_in_client):
    response = logged_in_client.post("/expense-categories", json={"description": "no name given"})
    assert response.status_code == 400
    assert "error" in response.get_json()


def test_create_expense_category_happy_path(logged_in_client):
    response = logged_in_client.post(
        "/expense-categories",
        json={"name": "Groceries", "description": "Weekly food shopping", "color": "#4CAF50"},
    )
    assert response.status_code == 201
    body = response.get_json()
    assert body["name"] == "Groceries"
    assert body["description"] == "Weekly food shopping"
    assert body["color"] == "#4CAF50"
    assert "id" in body
    assert "created_at" in body


def test_create_expense_category_rejects_duplicate_name(logged_in_client):
    first = logged_in_client.post("/expense-categories", json={"name": "Groceries"})
    assert first.status_code == 201

    second = logged_in_client.post("/expense-categories", json={"name": "Groceries"})
    assert second.status_code == 409
    assert "error" in second.get_json()
